### logout
GET http://localhost:5000/private/logout  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA4NjUwMTAsInVzZXJfaWQiOjF9.SrRzTyQ60c-Yk52WK0wwIExJCGM5og9umGLDi9CF-ss

### public
GET http://localhost:5000/public  HTTP/1.1

### private
GET http://localhost:5000/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA4NjUwMTAsInVzZXJfaWQiOjF9.SrRzTyQ60c-Yk52WK0wwIExJCGM5og9umGLDi9CF-ss
### signup
POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{
    "name":"Mwirigi",
    "email":"mwirigidan03@gmail.com",
    "password":"mwirigi"
}

### login
POST http://localhost:5000/login  HTTP/1.1
Content-Type: application/json

{
    "email":"mwirigidan03@gmail.com",
    "password":"mwirigi"
}